### ISSUE TITLE
Process for Reporting Security Vulnerabilities

### ISSUE THREAD

**Issue by 4cad** [jerryscript-project/iotjs#1893]
What is the best way to report security bugs to your project? It is a generally good practice to avoid public issue trackers if possible when reporting vulnerabilities, but I cannot find any alternatives in your project documentation.

Thanks,
Dane

**Comment by LaszloLango** [comment]
CC: @daeyeon @haesik

**Comment by 4cad** [comment]
Any thoughts on this? I would prefer not to sit on vulnerabilities for too long after their discovery.

**Comment by akosthekiss** [comment]
@4cad Hi Dane, the project has no official private channels at the moment. You can track down my email address from my profile page and I might try and give a feedback whether to publicly report the vulnerability or not, but that's far from official. (Or you might try that with any of the other [maintainers](https://github.com/lws-project/iotjs/wiki/Assigned-People).)

**Comment by 4cad** [comment]
@akosthekiss Sounds good - I will give you a ping tonight with the details.

**Comment by akosthekiss** [comment]
Issue discussed with @4cad via email. Closing this issue for now.
