### ISSUE TITLE
How can I use iotjs as an external library ?

### ISSUE THREAD

**Issue by yyykkkyyy** [jerryscript-project/iotjs#1939]
Hi, 

I would like to use iotjs in my project as an external library.
The build of the project will be used Makefile.
So, I consider the structure of the project...

```
project_dir/
          ├src/
          └libs/
               ├iotjs
                .....
```
If I define the structure of directory like above, how can I use iotjs in src directory?
Can I include and link whole iotjs directory in Makefile ?

**Comment by rzr** [comment]
Relate-to: https://github.com/jerryscript-project/iotjs/pull/1896
