### ISSUE TITLE
Logo creation

### ISSUE THREAD

**Issue by Seo-Young** [jerryscript-project/iotjs#285]
Just few minutes ago, I suggest to collaborate for an official logo of JerryScript. https://github.com/Samsung/jerryscript/issues/702

Same suggestion for IoT.js.
Please feel free post your idea into this thread.

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11057318/5ae6db88-87cd-11e5-8133-f63bbc33b020.png)

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11057403/fd610942-87cd-11e5-9c58-09055ef3403e.png)
This is suggested by @ILyoan .

**Comment by Seo-Young** [comment]
Reopen this issue for more candidates. 
Please feel free suggest candidates until 12/11.

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11491399/dc06004c-9824-11e5-8861-df9a119457bf.png)

**Comment by Seo-Young** [comment]
![image](https://cloud.githubusercontent.com/assets/5035570/11491495/adc38e38-9825-11e5-8cfa-d6a892774c16.png)

**Comment by lemmaa** [comment]
IoT.{JerryScript Logo}

**Comment by egavrin** [comment]
@lemmaa +1

**Comment by Seo-Young** [comment]
@lemmaa Then we have to wait for JerryScript logo decision :)

**Comment by davidsz** [comment]
Ideas for the IoT.{JS Logo} concept:
![logos-1](https://cloud.githubusercontent.com/assets/4364601/12394338/85a0eb5c-bdfb-11e5-835c-4f82f8d37910.png)

**Comment by esevan** [comment]
Combining ideas of @Seo-Young and @lemmaa 
![image](https://cloud.githubusercontent.com/assets/8223765/19677571/e0b1f0b6-9ad4-11e6-800f-352751235d15.png)

**Comment by zherczeg** [comment]
Hm, I would raise the JS logo, so it it would not be aligned to the bottom of I and T letters, but in the center.

    %%%  %%%%%
     % /%\ %
     % %%% %
     % \%/ %
    %%%    %

**Comment by rtakacs** [comment]
Just a note:

If the project will support other JS engines (see [wiki](https://github.com/Samsung/iotjs/wiki/Inside%20IoT.js#javascript-binding)) the logo should not refer to JerryScript.

**Comment by daeyeon** [comment]
No update for a long while. Please open this again if necessary.

**Comment by knightburton** [comment]
I would like to reopen this issue. There are a few application that can use the logo (like: [IoT.js Code](https://github.com/Samsung/iotjscode), [IoT.js VSCode extension](https://github.com/Samsung/iotjs-vscode-extension) ).

I have a concept based on the other's idea (I hope that the others will also upload their own concept).
![iotjs](https://user-images.githubusercontent.com/12102205/41299324-7c8d41ee-6e63-11e8-97ea-40daef229cf1.png)
![iotjs-2](https://user-images.githubusercontent.com/12102205/41299325-7cc8f4be-6e63-11e8-96da-97f838ecceea.png)

**Comment by akosthekiss** [comment]
All right, here is my version.
![iotjs-v3](https://user-images.githubusercontent.com/9976482/41300836-f985765a-6e66-11e8-8906-cbc68f66a685.png)

**Comment by zherczeg** [comment]
I like the logo from @akosthekiss but I would make the circles arund it smaller. Or maybe add color to the I T and .js text. (White O in the center is ok)

**Comment by rzr** [comment]
I like the "cartoon" style from @davidsz  that will suit with jerry script style:
https://github.com/Samsung/iotjs/issues/285#issuecomment-172551353

Myself I've attempted to create "a logo" (*cough* *cough*), which is just a comic strip bubble:

![webthing-iotjs-20180621rzr.gif](https://s-opensource.org/wp-content/uploads/2018/06/webthing-iotjs-20180621rzr.gif)

**Comment by LaszloLango** [comment]
I prefer the version of @akosthekiss . The text inside the logo is bit odd to me. The letter 'O' should be lowercase and the `.js` shouldn't be much smaller. Maybe the whole text should be on the same line. I wouldn't add more color to it.

**Comment by polaroi8d** [comment]
![iot](https://user-images.githubusercontent.com/9247788/41918606-fe73d354-795c-11e8-957d-51cddbdd6d29.png)

**Comment by LaszloLango** [comment]
@polaroi8d not bad, but I'd put the little circles into the foreground.

**Comment by polaroi8d** [comment]
@LaszloLango i will upload with your suggestions ;)
